// Fitness & Muscle Recovery recipes for high protein and lean nutrition
// Goal: Muscle repair, hormone support, high satiety, and optimal macro ratios
// Rich in Lean Protein, BCAAs, Zinc, and Recovery Nutrients

export const FITNESS_RECOVERY_RECIPES: any[] = [
  {
    id: "greek-yogurt-parfait-seeds",
    name: "Greek Yogurt Parfait with Seeds",
    description: "High casein protein content aids muscle repair overnight. Perfect post-workout or recovery meal with slow-digesting protein.",
    cuisine: "american",
    category: "meal-prep",
    cookingTime: 5,
    servings: 1,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Greek yogurt parfait seeds granola berries fitness protein",
    sourceUrl: "https://www.budgetbytes.com/tropical-yogurt-parfaits/",
    ingredients: [
      { name: "Greek yogurt (0% fat)", amount: "300g", estimatedPrice: 1.20 },
      { name: "Mixed berries", amount: "100g", estimatedPrice: 1.30 },
      { name: "Pumpkin seeds", amount: "20g", estimatedPrice: 0.40 },
      { name: "Chia seeds", amount: "10g", estimatedPrice: 0.30 },
      { name: "Honey", amount: "1 tbsp", estimatedPrice: 0.15 },
      { name: "Granola", amount: "30g", estimatedPrice: 0.40 }
    ],
    instructions: [
      "Layer half the Greek yogurt in a glass or bowl",
      "Add half the mixed berries",
      "Sprinkle with half the pumpkin and chia seeds",
      "Add remaining yogurt",
      "Top with remaining berries, seeds, and granola",
      "Drizzle with honey",
      "Can be prepared the night before and refrigerated"
    ],
    nutrition: {
      calories: 445,
      protein: 32,
      carbs: 52,
      fats: 12,
      fiber: 8,
      zinc: 2.5,
      vitamins: ["Calcium", "Vitamin D", "Probiotics"]
    },
    tags: ["high-protein", "muscle-recovery", "casein-protein", "no-cook", "post-workout"],
    benefits: ["Slow-digesting protein for overnight recovery", "High calcium for bone health", "Probiotic gut support", "Convenient grab-and-go"],
    suitableFor: ["athletes", "gym-goers", "fitness", "students"]
  },
  {
    id: "turkey-sausage-sweet-potato-hash",
    name: "Turkey Sausage & Sweet Potato Hash",
    description: "Lean protein paired with recovery carbs. Ideal post-workout meal to replenish glycogen and build muscle.",
    cuisine: "american",
    category: "one-pot",
    cookingTime: 25,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Turkey sausage sweet potato hash fitness breakfast protein",
    sourceUrl: "https://www.budgetbytes.com/sweet-potato-hash/",
    ingredients: [
      { name: "Turkey sausages (lean)", amount: "300g", estimatedPrice: 3.00 },
      { name: "Sweet potatoes", amount: "400g", estimatedPrice: 0.80 },
      { name: "Red pepper", amount: "1", estimatedPrice: 0.80 },
      { name: "Onion", amount: "1 medium", estimatedPrice: 0.30 },
      { name: "Eggs", amount: "2", estimatedPrice: 0.40 },
      { name: "Olive oil", amount: "1 tbsp", estimatedPrice: 0.10 },
      { name: "Smoked paprika", amount: "1 tsp", estimatedPrice: 0.10 }
    ],
    instructions: [
      "Dice sweet potatoes into small cubes, microwave for 5 minutes to soften",
      "Heat oil in large skillet, add sliced turkey sausages",
      "Cook sausages for 5 minutes until browned, remove and set aside",
      "In same pan, add diced onion and pepper, cook 3 minutes",
      "Add sweet potato cubes and paprika, cook for 8-10 minutes until crispy",
      "Return sausages to pan, create two wells",
      "Crack eggs into wells, cover and cook 3-4 minutes until eggs set",
      "Season with salt and pepper, serve hot"
    ],
    nutrition: {
      calories: 520,
      protein: 38,
      carbs: 48,
      fats: 18,
      fiber: 7,
      zinc: 3.2,
      vitamins: ["Vitamin A", "B12", "Iron"]
    },
    tags: ["high-protein", "recovery-carbs", "post-workout", "lean-protein", "breakfast"],
    benefits: ["Lean turkey protein for muscle repair", "Complex carbs replenish glycogen", "Balanced macros", "High satiety"],
    suitableFor: ["athletes", "gym-goers", "fitness", "muscle-gain"]
  },
  {
    id: "grilled-chicken-quinoa-salad",
    name: "Grilled Chicken & Quinoa Salad",
    description: "The gold standard for clean fitness meals. Complete protein from chicken and quinoa with fresh vegetables.",
    cuisine: "american",
    category: "meal-prep",
    cookingTime: 30,
    servings: 3,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Grilled chicken quinoa salad fitness clean eating meal prep",
    sourceUrl: "https://www.recipetineats.com/my-favourite-quinoa-salad/",
    ingredients: [
      { name: "Chicken breast", amount: "450g", estimatedPrice: 3.20 },
      { name: "Quinoa", amount: "200g", estimatedPrice: 1.20 },
      { name: "Cherry tomatoes", amount: "200g", estimatedPrice: 1.00 },
      { name: "Cucumber", amount: "1", estimatedPrice: 0.60 },
      { name: "Feta cheese", amount: "60g", estimatedPrice: 0.80 },
      { name: "Lemon", amount: "1", estimatedPrice: 0.30 },
      { name: "Olive oil", amount: "2 tbsp", estimatedPrice: 0.20 },
      { name: "Fresh parsley", amount: "20g", estimatedPrice: 0.40 }
    ],
    instructions: [
      "Cook quinoa according to package instructions, let cool",
      "Season chicken breasts with salt, pepper, and lemon juice",
      "Grill or pan-fry chicken for 6-7 minutes each side until cooked through",
      "Let chicken rest 5 minutes, then slice into strips",
      "Dice cucumber and halve cherry tomatoes",
      "Combine quinoa, vegetables, and crumbled feta in large bowl",
      "Make dressing: whisk olive oil, lemon juice, salt, and pepper",
      "Add sliced chicken, pour dressing, garnish with parsley",
      "Divide into meal prep containers for 3 days"
    ],
    nutrition: {
      calories: 465,
      protein: 42,
      carbs: 40,
      fats: 14,
      fiber: 6,
      zinc: 2.8,
      vitamins: ["B6", "Niacin", "Selenium"]
    },
    tags: ["high-protein", "meal-prep", "clean-eating", "balanced-macros", "lean-protein"],
    benefits: ["Complete amino acid profile", "Meal prep friendly", "Balanced macros for fitness", "High satiety"],
    suitableFor: ["athletes", "gym-goers", "fitness", "meal-preppers"]
  },
  {
    id: "bison-burgers",
    name: "Bison Burgers",
    description: "Leaner than beef with a higher protein-to-fat ratio. Nutrient-dense red meat alternative for muscle building.",
    cuisine: "american",
    category: "one-pot",
    cookingTime: 15,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Bison burger lean protein fitness healthy red meat",
    sourceUrl: "https://www.recipetineats.com/hamburger-recipe/",
    ingredients: [
      { name: "Ground bison (or extra lean beef)", amount: "400g", estimatedPrice: 5.50 },
      { name: "Wholemeal burger buns", amount: "2", estimatedPrice: 0.80 },
      { name: "Lettuce", amount: "4 leaves", estimatedPrice: 0.20 },
      { name: "Tomato", amount: "1", estimatedPrice: 0.40 },
      { name: "Red onion", amount: "1 small", estimatedPrice: 0.25 },
      { name: "Low-fat cheese", amount: "2 slices", estimatedPrice: 0.50 },
      { name: "Worcestershire sauce", amount: "1 tbsp", estimatedPrice: 0.15 }
    ],
    instructions: [
      "Mix ground bison with Worcestershire sauce, salt, and pepper",
      "Form into 2 large patties (don't overwork the meat)",
      "Heat grill pan or skillet over medium-high heat",
      "Cook burgers 4-5 minutes per side for medium doneness",
      "Add cheese slice in last minute to melt",
      "Toast burger buns lightly",
      "Assemble: bun, lettuce, burger with cheese, tomato, onion",
      "Serve with sweet potato wedges or salad"
    ],
    nutrition: {
      calories: 485,
      protein: 52,
      carbs: 32,
      fats: 15,
      fiber: 5,
      zinc: 6.5,
      vitamins: ["B12", "Iron", "Selenium"]
    },
    tags: ["high-protein", "lean-red-meat", "muscle-building", "iron-rich", "zinc-rich"],
    benefits: ["Higher protein than regular beef", "Lower fat content", "Rich in iron and zinc", "Supports testosterone production"],
    suitableFor: ["athletes", "gym-goers", "fitness", "muscle-gain"]
  },
  {
    id: "turkey-hummus-wrap",
    name: "Turkey & Hummus Wrap",
    description: "High protein turkey combined with plant-based protein from chickpeas. Perfect portable fitness meal.",
    cuisine: "mediterranean",
    category: "meal-prep",
    cookingTime: 5,
    servings: 1,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Turkey hummus wrap fitness protein healthy lunch",
    sourceUrl: "https://www.budgetbytes.com/roasted-red-pepper-hummus-wraps/",
    ingredients: [
      { name: "Wholemeal tortilla wrap", amount: "1 large", estimatedPrice: 0.30 },
      { name: "Turkey breast slices (cooked)", amount: "120g", estimatedPrice: 2.00 },
      { name: "Hummus", amount: "60g", estimatedPrice: 0.50 },
      { name: "Spinach leaves", amount: "30g", estimatedPrice: 0.30 },
      { name: "Cucumber", amount: "50g", estimatedPrice: 0.20 },
      { name: "Cherry tomatoes", amount: "50g", estimatedPrice: 0.30 },
      { name: "Red pepper", amount: "50g", estimatedPrice: 0.30 }
    ],
    instructions: [
      "Lay tortilla wrap flat on clean surface",
      "Spread hummus evenly across the wrap, leaving 2cm border",
      "Layer turkey breast slices down the center",
      "Add spinach leaves, sliced cucumber, and halved tomatoes",
      "Add sliced red pepper strips",
      "Fold in the sides of the wrap, then roll tightly from bottom to top",
      "Cut in half diagonally",
      "Wrap in foil or parchment for portable meal"
    ],
    nutrition: {
      calories: 385,
      protein: 35,
      carbs: 42,
      fats: 9,
      fiber: 8,
      zinc: 2.0,
      vitamins: ["B6", "Niacin", "Folate"]
    },
    tags: ["high-protein", "portable", "meal-prep", "lean-protein", "plant-protein"],
    benefits: ["Dual protein sources (animal + plant)", "High fiber for satiety", "Portable lunch", "Low fat"],
    suitableFor: ["athletes", "gym-goers", "fitness", "students", "office-workers"]
  },
  {
    id: "tuna-salad-stuffed-peppers",
    name: "Tuna Salad Stuffed Peppers",
    description: "Almost pure protein with very low calories. Perfect for cutting phases while maintaining muscle mass.",
    cuisine: "mediterranean",
    category: "meal-prep",
    cookingTime: 10,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Tuna salad stuffed peppers fitness low calorie protein",
    sourceUrl: "https://www.budgetbytes.com/sweet-and-spicy-tuna-salad/",
    ingredients: [
      { name: "Tuna chunks in water (tinned)", amount: "2 x 160g", estimatedPrice: 2.00 },
      { name: "Bell peppers", amount: "2 large", estimatedPrice: 1.60 },
      { name: "Greek yogurt (0% fat)", amount: "60g", estimatedPrice: 0.30 },
      { name: "Celery", amount: "2 stalks", estimatedPrice: 0.30 },
      { name: "Red onion", amount: "1 small", estimatedPrice: 0.25 },
      { name: "Dijon mustard", amount: "1 tsp", estimatedPrice: 0.10 },
      { name: "Lemon juice", amount: "1 tbsp", estimatedPrice: 0.10 },
      { name: "Fresh dill", amount: "10g", estimatedPrice: 0.30 }
    ],
    instructions: [
      "Cut bell peppers in half lengthwise, remove seeds and membranes",
      "Drain tuna thoroughly and place in mixing bowl",
      "Finely dice celery and red onion",
      "Mix tuna with Greek yogurt, mustard, lemon juice, and chopped dill",
      "Add diced celery and onion, mix well",
      "Season with salt and black pepper to taste",
      "Spoon tuna mixture into pepper halves",
      "Serve immediately or refrigerate for meal prep (up to 3 days)"
    ],
    nutrition: {
      calories: 220,
      protein: 34,
      carbs: 12,
      fats: 4,
      fiber: 3,
      zinc: 1.2,
      vitamins: ["Vitamin C", "B12", "Omega-3"]
    },
    tags: ["high-protein", "low-calorie", "low-fat", "cutting-diet", "meal-prep"],
    benefits: ["Extremely high protein density", "Very low calories and fat", "Omega-3 for recovery", "Perfect for cutting phases"],
    suitableFor: ["athletes", "gym-goers", "fitness", "cutting", "weight-loss"]
  },
  {
    id: "chicken-avocado-caprese",
    name: "Chicken & Avocado Caprese",
    description: "High protein with healthy fats for hormonal health. Supports testosterone production and muscle recovery.",
    cuisine: "italian",
    category: "meal-prep",
    cookingTime: 15,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Chicken avocado caprese fitness healthy fats protein",
    sourceUrl: "https://www.recipetineats.com/caprese-salad/",
    ingredients: [
      { name: "Chicken breast", amount: "2 x 150g", estimatedPrice: 2.20 },
      { name: "Avocado", amount: "1 large", estimatedPrice: 0.90 },
      { name: "Mozzarella (light)", amount: "125g", estimatedPrice: 1.20 },
      { name: "Cherry tomatoes", amount: "200g", estimatedPrice: 1.00 },
      { name: "Fresh basil", amount: "15g", estimatedPrice: 0.50 },
      { name: "Balsamic glaze", amount: "2 tbsp", estimatedPrice: 0.40 },
      { name: "Olive oil", amount: "1 tbsp", estimatedPrice: 0.10 }
    ],
    instructions: [
      "Season chicken breasts with salt, pepper, and Italian herbs",
      "Grill or pan-fry chicken in olive oil for 6-7 minutes each side",
      "Let chicken rest 5 minutes, then slice",
      "Slice mozzarella and avocado",
      "Halve cherry tomatoes",
      "Arrange chicken slices on plate, top with mozzarella, avocado, and tomatoes",
      "Tear fresh basil leaves and sprinkle over",
      "Drizzle with balsamic glaze",
      "Serve with mixed greens or quinoa"
    ],
    nutrition: {
      calories: 495,
      protein: 45,
      carbs: 18,
      fats: 26,
      fiber: 7,
      zinc: 2.5,
      vitamins: ["Vitamin E", "B6", "Folate", "Healthy Fats"]
    },
    tags: ["high-protein", "healthy-fats", "hormone-support", "keto-friendly", "low-carb"],
    benefits: ["Healthy fats support testosterone", "High protein for muscle", "Antioxidants from avocado", "Hormone optimization"],
    suitableFor: ["athletes", "gym-goers", "fitness", "muscle-gain", "keto"]
  },
  {
    id: "grilled-tempeh-broccoli-bowl",
    name: "Grilled Tempeh & Broccoli Bowl",
    description: "A complete plant-based protein source. Fermented soy provides all essential amino acids for muscle building.",
    cuisine: "chinese",
    category: "one-pot",
    cookingTime: 20,
    servings: 2,
    difficulty: "medium",
    spiceLevel: "medium",
    authentic: false,
    imageQuery: "Grilled tempeh broccoli bowl vegan fitness protein",
    sourceUrl: "https://minimalistbaker.com/simple-vegetable-tempeh-stir-fry/",
    ingredients: [
      { name: "Tempeh", amount: "300g", estimatedPrice: 2.50 },
      { name: "Broccoli florets", amount: "300g", estimatedPrice: 1.00 },
      { name: "Brown rice", amount: "200g cooked", estimatedPrice: 0.40 },
      { name: "Soy sauce", amount: "3 tbsp", estimatedPrice: 0.20 },
      { name: "Sesame oil", amount: "1 tbsp", estimatedPrice: 0.30 },
      { name: "Ginger", amount: "1 tbsp fresh", estimatedPrice: 0.25 },
      { name: "Garlic cloves", amount: "3", estimatedPrice: 0.15 },
      { name: "Sesame seeds", amount: "1 tbsp", estimatedPrice: 0.15 }
    ],
    instructions: [
      "Slice tempeh into 1cm thick strips",
      "Marinate tempeh in soy sauce, minced ginger, and garlic for 10 minutes",
      "Steam broccoli florets for 5 minutes until tender-crisp",
      "Heat sesame oil in large pan or grill pan",
      "Grill tempeh strips for 3-4 minutes each side until golden and crispy",
      "Add broccoli to pan, toss with remaining marinade for 2 minutes",
      "Serve over brown rice",
      "Garnish with sesame seeds"
    ],
    nutrition: {
      calories: 526,
      protein: 23,
      carbs: 54,
      fats: 26,
      fiber: 10,
      zinc: 2.0,
      vitamins: ["Iron", "Calcium", "Probiotics", "Vitamin K"]
    },
    tags: ["vegan", "plant-protein", "complete-protein", "high-fiber", "fermented"],
    benefits: ["Complete plant protein with all amino acids", "Fermented for gut health", "High fiber for satiety", "Vegan muscle building"],
    suitableFor: ["athletes", "gym-goers", "fitness", "vegans", "vegetarians"]
  },
  {
    id: "tofu-scramble-kale",
    name: "Tofu Scramble with Kale",
    description: "High protein vegan alternative to eggs. Perfect breakfast for plant-based athletes and muscle recovery.",
    cuisine: "american",
    category: "one-pot",
    cookingTime: 15,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Tofu scramble kale vegan fitness protein breakfast",
    sourceUrl: "https://minimalistbaker.com/southwest-tofu-scramble/",
    ingredients: [
      { name: "Firm tofu", amount: "400g", estimatedPrice: 1.80 },
      { name: "Kale", amount: "150g", estimatedPrice: 1.00 },
      { name: "Cherry tomatoes", amount: "100g", estimatedPrice: 0.50 },
      { name: "Onion", amount: "1 medium", estimatedPrice: 0.30 },
      { name: "Turmeric", amount: "1 tsp", estimatedPrice: 0.10 },
      { name: "Nutritional yeast", amount: "2 tbsp", estimatedPrice: 0.40 },
      { name: "Olive oil", amount: "1 tbsp", estimatedPrice: 0.10 },
      { name: "Wholemeal toast", amount: "2 slices", estimatedPrice: 0.30 }
    ],
    instructions: [
      "Drain tofu and crumble into small pieces with hands or fork",
      "Heat olive oil in large pan, sauté diced onion until soft (3 minutes)",
      "Add crumbled tofu, turmeric, salt, and pepper",
      "Cook for 5 minutes, stirring occasionally, until tofu is golden",
      "Add chopped kale and halved tomatoes, cook 3 minutes until kale wilts",
      "Stir in nutritional yeast for cheesy flavor",
      "Season to taste with salt and black pepper",
      "Serve over wholemeal toast"
    ],
    nutrition: {
      calories: 332,
      protein: 21,
      carbs: 32,
      fats: 15,
      fiber: 4,
      zinc: 2.2,
      vitamins: ["Iron", "Calcium", "Vitamin K", "B12 (from yeast)"]
    },
    tags: ["vegan", "plant-protein", "high-fiber", "breakfast", "dairy-free"],
    benefits: ["High plant protein", "Iron-rich kale prevents fatigue", "Calcium for bones", "Cholesterol-free"],
    suitableFor: ["athletes", "gym-goers", "fitness", "vegans", "vegetarians"]
  },
  {
    id: "spinach-feta-mushroom-omelet",
    name: "Spinach, Feta, & Mushroom Omelet",
    description: "Eggs provide the most bioavailable protein. Perfect muscle recovery breakfast with complete amino acids.",
    cuisine: "mediterranean",
    category: "one-pot",
    cookingTime: 10,
    servings: 1,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Spinach feta mushroom omelet fitness protein breakfast",
    sourceUrl: "https://www.budgetbytes.com/scrambled-eggs-with-spinach-and-feta/",
    ingredients: [
      { name: "Eggs", amount: "3 large", estimatedPrice: 0.60 },
      { name: "Fresh spinach", amount: "50g", estimatedPrice: 0.30 },
      { name: "Mushrooms", amount: "60g", estimatedPrice: 0.40 },
      { name: "Feta cheese", amount: "40g", estimatedPrice: 0.50 },
      { name: "Butter", amount: "10g", estimatedPrice: 0.10 },
      { name: "Milk", amount: "2 tbsp", estimatedPrice: 0.10 },
      { name: "Wholemeal toast", amount: "1 slice", estimatedPrice: 0.15 }
    ],
    instructions: [
      "Whisk eggs with milk, salt, and pepper until well combined",
      "Slice mushrooms thinly",
      "Heat butter in non-stick pan over medium heat",
      "Sauté mushrooms for 2 minutes until softened",
      "Add spinach, cook for 1 minute until wilted, remove and set aside",
      "Pour egg mixture into same pan, swirl to cover base",
      "Cook for 2-3 minutes until edges set but center still slightly runny",
      "Add mushroom-spinach mixture and crumbled feta to one half",
      "Fold omelet in half, cook 1 more minute",
      "Serve with wholemeal toast"
    ],
    nutrition: {
      calories: 390,
      protein: 24,
      carbs: 18,
      fats: 23,
      fiber: 3,
      zinc: 2.8,
      vitamins: ["B12", "Vitamin D", "Choline", "Selenium"]
    },
    tags: ["high-protein", "bioavailable-protein", "breakfast", "keto-friendly", "quick"],
    benefits: ["Most bioavailable protein source", "Complete amino acid profile", "Choline for brain health", "Quick muscle recovery"],
    suitableFor: ["athletes", "gym-goers", "fitness", "students", "muscle-gain"]
  },
  {
    id: "leftover-roast-beef-rollups",
    name: "Leftover Roast Beef Roll-ups",
    description: "Pure protein snack or meal. Perfect high-protein, low-carb option for muscle maintenance and cutting.",
    cuisine: "american",
    category: "meal-prep",
    cookingTime: 5,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Roast beef rollups protein fitness low carb snack",
    sourceUrl: "https://bowl-me-over.com/roast-beef-rollups-recipe/",
    ingredients: [
      { name: "Lean roast beef slices", amount: "200g", estimatedPrice: 3.50 },
      { name: "Cream cheese (light)", amount: "60g", estimatedPrice: 0.60 },
      { name: "Rocket/Arugula", amount: "40g", estimatedPrice: 0.50 },
      { name: "Cherry tomatoes", amount: "80g", estimatedPrice: 0.40 },
      { name: "Horseradish sauce", amount: "1 tbsp", estimatedPrice: 0.20 },
      { name: "Cucumber", amount: "100g", estimatedPrice: 0.30 }
    ],
    instructions: [
      "Lay roast beef slices flat on clean surface",
      "Mix cream cheese with horseradish sauce",
      "Spread a thin layer of cream cheese mixture on each slice",
      "Add a few rocket leaves to each slice",
      "Cut cucumber into thin strips (matchsticks)",
      "Place cucumber strip on each beef slice",
      "Roll tightly and secure with toothpick if needed",
      "Serve with cherry tomatoes on the side",
      "Can be made ahead and refrigerated for quick snacks"
    ],
    nutrition: {
      calories: 255,
      protein: 28,
      carbs: 6,
      fats: 13,
      fiber: 2,
      zinc: 5.5,
      vitamins: ["B12", "Iron", "Zinc"]
    },
    tags: ["high-protein", "low-carb", "keto", "no-cook", "portable-snack"],
    benefits: ["Almost pure protein", "Very low carb for cutting", "High zinc and iron", "Quick energy"],
    suitableFor: ["athletes", "gym-goers", "fitness", "cutting", "keto"]
  },
  {
    id: "shrimp-whole-wheat-pasta",
    name: "Shrimp & Whole Wheat Pasta",
    description: "Shrimp is incredibly lean and protein-dense. Perfect combination of protein and complex carbs for muscle recovery.",
    cuisine: "italian",
    category: "one-pot",
    cookingTime: 20,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Shrimp whole wheat pasta fitness lean protein Italian",
    sourceUrl: "https://www.recipetineats.com/creamy-garlic-prawn-pasta/",
    ingredients: [
      { name: "King prawns/shrimp", amount: "300g", estimatedPrice: 4.00 },
      { name: "Whole wheat pasta", amount: "200g", estimatedPrice: 0.80 },
      { name: "Cherry tomatoes", amount: "200g", estimatedPrice: 1.00 },
      { name: "Garlic cloves", amount: "4", estimatedPrice: 0.20 },
      { name: "Fresh spinach", amount: "100g", estimatedPrice: 0.60 },
      { name: "Olive oil", amount: "2 tbsp", estimatedPrice: 0.20 },
      { name: "Lemon", amount: "1", estimatedPrice: 0.30 },
      { name: "Red pepper flakes", amount: "1/2 tsp", estimatedPrice: 0.05 }
    ],
    instructions: [
      "Cook whole wheat pasta according to package instructions, drain (reserve 1 cup pasta water)",
      "Heat olive oil in large pan, add minced garlic and red pepper flakes",
      "Cook garlic for 1 minute until fragrant",
      "Add prawns, cook 2-3 minutes per side until pink and opaque",
      "Add halved cherry tomatoes, cook 3 minutes until softened",
      "Add spinach and cook until wilted (1 minute)",
      "Toss in cooked pasta with a splash of pasta water",
      "Squeeze lemon juice over, season with salt and pepper",
      "Serve immediately with extra lemon wedges"
    ],
    nutrition: {
      calories: 485,
      protein: 42,
      carbs: 58,
      fats: 10,
      fiber: 9,
      zinc: 2.5,
      vitamins: ["B12", "Selenium", "Vitamin D", "Omega-3"]
    },
    tags: ["high-protein", "lean-protein", "complex-carbs", "low-fat", "post-workout"],
    benefits: ["Very lean protein source", "Complex carbs for recovery", "Low fat, high protein density", "Omega-3 for inflammation"],
    suitableFor: ["athletes", "gym-goers", "fitness", "students", "muscle-gain"]
  },
  {
    id: "stuffed-acorn-squash-turkey",
    name: "Stuffed Acorn Squash with Turkey",
    description: "Lean ground turkey provides high satiety. Nutrient-dense meal with slow-digesting carbs and lean protein.",
    cuisine: "american",
    category: "one-pot",
    cookingTime: 45,
    servings: 2,
    difficulty: "medium",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Stuffed acorn squash turkey fitness healthy meal",
    sourceUrl: "https://www.budgetbytes.com/wild-rice-stuffed-acorn-squash/",
    ingredients: [
      { name: "Acorn squash", amount: "1 large", estimatedPrice: 1.80 },
      { name: "Lean turkey mince", amount: "300g", estimatedPrice: 3.00 },
      { name: "Quinoa", amount: "100g", estimatedPrice: 0.60 },
      { name: "Cranberries (dried)", amount: "40g", estimatedPrice: 0.50 },
      { name: "Onion", amount: "1 small", estimatedPrice: 0.30 },
      { name: "Pecans (chopped)", amount: "30g", estimatedPrice: 0.60 },
      { name: "Sage (dried)", amount: "1 tsp", estimatedPrice: 0.10 },
      { name: "Olive oil", amount: "1 tbsp", estimatedPrice: 0.10 }
    ],
    instructions: [
      "Preheat oven to 200°C. Cut acorn squash in half lengthwise, scoop out seeds",
      "Brush squash halves with olive oil, season with salt and pepper",
      "Place cut-side down on baking tray, roast for 30 minutes until tender",
      "Meanwhile, cook quinoa according to package instructions",
      "Sauté diced onion in pan until soft (3 minutes)",
      "Add turkey mince, break up and cook until browned (8 minutes)",
      "Stir in cooked quinoa, cranberries, chopped pecans, and sage",
      "Season with salt and pepper",
      "Flip squash halves over, fill with turkey-quinoa mixture",
      "Return to oven for 10 minutes to heat through",
      "Serve hot"
    ],
    nutrition: {
      calories: 565,
      protein: 42,
      carbs: 62,
      fats: 16,
      fiber: 10,
      zinc: 3.8,
      vitamins: ["Vitamin A", "B6", "Magnesium"]
    },
    tags: ["high-protein", "complex-carbs", "high-fiber", "nutrient-dense", "complete-meal"],
    benefits: ["High satiety from fiber and protein", "Slow-digesting carbs", "Nutrient-dense squash", "Balanced macros"],
    suitableFor: ["athletes", "gym-goers", "fitness", "students", "muscle-gain"]
  },
  {
    id: "lemon-herb-roasted-chicken-thighs",
    name: "Lemon Herb Roasted Chicken Thighs",
    description: "Zinc and protein for testosterone and hormone support. Dark meat provides more minerals than breast meat.",
    cuisine: "mediterranean",
    category: "one-pot",
    cookingTime: 40,
    servings: 3,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Lemon herb roasted chicken thighs fitness protein zinc",
    sourceUrl: "https://www.budgetbytes.com/garlic-butter-baked-chicken-thighs/",
    ingredients: [
      { name: "Chicken thighs (skin-on)", amount: "6 pieces (700g)", estimatedPrice: 3.50 },
      { name: "Lemon", amount: "2", estimatedPrice: 0.60 },
      { name: "Garlic cloves", amount: "6", estimatedPrice: 0.30 },
      { name: "Fresh rosemary", amount: "3 sprigs", estimatedPrice: 0.40 },
      { name: "Fresh thyme", amount: "3 sprigs", estimatedPrice: 0.40 },
      { name: "Olive oil", amount: "2 tbsp", estimatedPrice: 0.20 },
      { name: "Baby potatoes", amount: "400g", estimatedPrice: 0.80 }
    ],
    instructions: [
      "Preheat oven to 200°C",
      "In large bowl, mix olive oil, juice of 1 lemon, minced garlic, and herbs",
      "Add chicken thighs and halved baby potatoes, toss to coat",
      "Arrange in roasting tin, place lemon slices under and around chicken",
      "Season generously with salt and pepper",
      "Roast for 35-40 minutes until chicken skin is crispy and internal temp reaches 75°C",
      "Let rest 5 minutes before serving",
      "Squeeze remaining lemon over chicken before eating"
    ],
    nutrition: {
      calories: 380,
      protein: 28,
      carbs: 28,
      fats: 18,
      fiber: 3,
      zinc: 4.2,
      vitamins: ["B12", "Selenium", "Iron", "Niacin"]
    },
    tags: ["high-protein", "zinc-rich", "hormone-support", "one-pan", "meal-prep"],
    benefits: ["High zinc for testosterone production", "More minerals than white meat", "Hormone optimization", "High satiety"],
    suitableFor: ["athletes", "gym-goers", "fitness", "muscle-gain", "men"]
  },
  {
    id: "cottage-cheese-bowl",
    name: "Cottage Cheese Bowl",
    description: "High protein density with slow-digesting casein. Perfect bedtime snack for overnight muscle recovery.",
    cuisine: "american",
    category: "meal-prep",
    cookingTime: 3,
    servings: 1,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Cottage cheese bowl fitness protein casein recovery",
    sourceUrl: "https://www.budgetbytes.com/cottage-cheese-breakfast-bowls-6-ways/",
    ingredients: [
      { name: "Cottage cheese (low-fat)", amount: "250g", estimatedPrice: 1.30 },
      { name: "Mixed berries", amount: "80g", estimatedPrice: 1.00 },
      { name: "Almonds (sliced)", amount: "20g", estimatedPrice: 0.40 },
      { name: "Honey", amount: "1 tsp", estimatedPrice: 0.10 },
      { name: "Cinnamon", amount: "1/2 tsp", estimatedPrice: 0.05 }
    ],
    instructions: [
      "Place cottage cheese in serving bowl",
      "Top with mixed berries",
      "Sprinkle with sliced almonds",
      "Drizzle with honey",
      "Dust with cinnamon",
      "Serve immediately or refrigerate for later",
      "Perfect as bedtime snack for overnight recovery"
    ],
    nutrition: {
      calories: 325,
      protein: 32,
      carbs: 28,
      fats: 9,
      fiber: 5,
      zinc: 1.5,
      vitamins: ["Calcium", "B12", "Probiotics"]
    },
    tags: ["high-protein", "casein-protein", "bedtime-snack", "recovery", "no-cook"],
    benefits: ["Slow-digesting casein for overnight recovery", "High protein density", "Low fat option", "Calcium for bones"],
    suitableFor: ["athletes", "gym-goers", "fitness", "students", "muscle-gain"]
  },
  {
    id: "ricotta-berry-toast",
    name: "Ricotta & Berry Toast",
    description: "Whey and casein protein blend. Quick breakfast with balanced protein for sustained muscle protein synthesis.",
    cuisine: "italian",
    category: "meal-prep",
    cookingTime: 5,
    servings: 1,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Ricotta berry toast fitness protein breakfast healthy",
    sourceUrl: "https://www.budgetbytes.com/ricotta-toast-4-ways/",
    ingredients: [
      { name: "Wholemeal sourdough bread", amount: "2 slices", estimatedPrice: 0.60 },
      { name: "Ricotta cheese", amount: "100g", estimatedPrice: 0.80 },
      { name: "Mixed berries", amount: "80g", estimatedPrice: 1.00 },
      { name: "Honey", amount: "1 tsp", estimatedPrice: 0.10 },
      { name: "Mint leaves", amount: "5 leaves", estimatedPrice: 0.10 }
    ],
    instructions: [
      "Toast bread slices until golden and crispy",
      "Spread ricotta cheese generously on each slice",
      "Top with fresh mixed berries",
      "Drizzle with honey",
      "Tear mint leaves and sprinkle over",
      "Serve immediately while toast is warm",
      "Optional: add a sprinkle of cinnamon or crushed pistachios"
    ],
    nutrition: {
      calories: 400,
      protein: 16,
      carbs: 48,
      fats: 12,
      fiber: 4,
      zinc: 1.8,
      vitamins: ["Calcium", "B12", "Vitamin C"]
    },
    tags: ["breakfast", "protein-blend", "quick", "vegetarian", "balanced"],
    benefits: ["Whey + casein protein for sustained release", "Quick breakfast option", "Balanced macros", "Antioxidants from berries"],
    suitableFor: ["athletes", "gym-goers", "fitness", "students", "busy-mornings"]
  },
  {
    id: "protein-buckwheat-pancakes",
    name: "Protein Buckwheat Pancakes",
    description: "Customizable for macros with added protein powder. Perfect pre or post-workout breakfast for muscle building.",
    cuisine: "american",
    category: "one-pot",
    cookingTime: 15,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Protein pancakes fitness buckwheat breakfast muscle building",
    sourceUrl: "https://minimalistbaker.com/1-bowl-peanut-butter-protein-pancakes/",
    ingredients: [
      { name: "Buckwheat flour", amount: "100g", estimatedPrice: 0.80 },
      { name: "Protein powder (vanilla)", amount: "30g (1 scoop)", estimatedPrice: 1.20 },
      { name: "Eggs", amount: "2", estimatedPrice: 0.40 },
      { name: "Banana (mashed)", amount: "1 medium", estimatedPrice: 0.20 },
      { name: "Milk", amount: "150ml", estimatedPrice: 0.20 },
      { name: "Baking powder", amount: "1 tsp", estimatedPrice: 0.05 },
      { name: "Greek yogurt (to serve)", amount: "100g", estimatedPrice: 0.50 },
      { name: "Berries (to serve)", amount: "100g", estimatedPrice: 1.20 }
    ],
    instructions: [
      "Mash banana in large bowl",
      "Add eggs, milk, and mix well",
      "Combine buckwheat flour, protein powder, and baking powder",
      "Add dry ingredients to wet, mix until smooth (don't overmix)",
      "Heat non-stick pan over medium heat, lightly grease",
      "Pour 1/4 cup batter per pancake",
      "Cook 2-3 minutes until bubbles form, flip and cook 2 more minutes",
      "Stack pancakes, top with Greek yogurt and berries",
      "Optional: drizzle with honey or maple syrup"
    ],
    nutrition: {
      calories: 485,
      protein: 35,
      carbs: 62,
      fats: 10,
      fiber: 8,
      zinc: 2.5,
      vitamins: ["B-complex", "Magnesium", "BCAAs from protein powder"]
    },
    tags: ["high-protein", "pre-workout", "post-workout", "customizable-macros", "breakfast"],
    benefits: ["Customizable protein content", "Slow-burning buckwheat carbs", "Complete breakfast", "Muscle building"],
    suitableFor: ["athletes", "gym-goers", "fitness", "muscle-gain", "students"]
  }
];
