// Work efficiency recipes for sustained energy and mental clarity
// Goal: Prevent fatigue, avoid afternoon slump, maintain focus during work
// Rich in Iron, B-vitamins, Complex Carbs, and Fiber

export const WORK_EFFICIENCY_RECIPES: any[] = [
  {
    id: "quinoa-breakfast-bowl",
    name: "Quinoa Breakfast Bowl",
    description: "Complete protein and complex carbs for 4+ hours of steady energy. Perfect for powering through morning meetings and tasks.",
    cuisine: "american",
    category: "meal-prep",
    cookingTime: 20,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Quinoa breakfast bowl with berries nuts healthy energy food",
    sourceUrl: "https://minimalistbaker.com/dark-chocolate-quinoa-breakfast-bowl/",
    ingredients: [
      { name: "Quinoa", amount: "200g", estimatedPrice: 1.20 },
      { name: "Almond milk", amount: "400ml", estimatedPrice: 0.80 },
      { name: "Mixed berries", amount: "150g", estimatedPrice: 2.00 },
      { name: "Almonds (sliced)", amount: "30g", estimatedPrice: 0.60 },
      { name: "Honey", amount: "2 tbsp", estimatedPrice: 0.30 },
      { name: "Cinnamon", amount: "1 tsp", estimatedPrice: 0.10 },
      { name: "Banana", amount: "1 medium", estimatedPrice: 0.20 }
    ],
    instructions: [
      "Rinse quinoa thoroughly under cold water",
      "Combine quinoa and almond milk in a pot, bring to boil then reduce to simmer for 15 minutes",
      "Once quinoa is fluffy and liquid absorbed, remove from heat",
      "Stir in cinnamon and honey while still warm",
      "Top with mixed berries, sliced banana, and almonds",
      "Can be made in batches and reheated for quick breakfasts"
    ],
    nutrition: {
      calories: 350,
      protein: 10,
      carbs: 55,
      fats: 10,
      fiber: 6,
      iron: 3.5,
      vitamins: ["B-complex", "Vitamin E"]
    },
    tags: ["breakfast", "high-protein", "meal-prep", "energy-boost", "work-fuel"],
    benefits: ["Sustained energy for 4+ hours", "Complete protein", "Prevents mid-morning crashes", "Brain-boosting nutrients"],
    suitableFor: ["students", "office-workers", "early-risers", "meal-preppers"]
  },
  {
    id: "lentil-soup-spinach",
    name: "Lentil Soup with Spinach",
    description: "Iron-rich lentils prevent fatigue while spinach adds folate for mental clarity. A warming one-pot wonder for sustained work energy.",
    cuisine: "mediterranean",
    category: "one-pot",
    cookingTime: 35,
    servings: 4,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: true,
    imageQuery: "Lentil spinach soup healthy iron-rich comfort food",
    sourceUrl: "https://www.budgetbytes.com/creamy-coconut-curry-lentils-with-spinach/",
    ingredients: [
      { name: "Red lentils", amount: "250g", estimatedPrice: 0.80 },
      { name: "Fresh spinach", amount: "200g", estimatedPrice: 1.20 },
      { name: "Onion", amount: "1 large", estimatedPrice: 0.30 },
      { name: "Garlic cloves", amount: "3", estimatedPrice: 0.15 },
      { name: "Vegetable stock", amount: "1.2L", estimatedPrice: 0.50 },
      { name: "Cumin", amount: "1 tsp", estimatedPrice: 0.10 },
      { name: "Olive oil", amount: "2 tbsp", estimatedPrice: 0.20 },
      { name: "Lemon juice", amount: "2 tbsp", estimatedPrice: 0.15 }
    ],
    instructions: [
      "Heat olive oil in a large pot, sauté chopped onion until soft (5 minutes)",
      "Add minced garlic and cumin, cook for 1 minute until fragrant",
      "Add lentils and vegetable stock, bring to boil",
      "Reduce heat and simmer for 25 minutes until lentils are tender",
      "Stir in fresh spinach and cook for 2-3 minutes until wilted",
      "Add lemon juice, season with salt and pepper to taste",
      "Blend partially for creamy texture if desired"
    ],
    nutrition: {
      calories: 370,
      protein: 15,
      carbs: 50,
      fats: 14,
      fiber: 10,
      iron: 6.8,
      vitamins: ["Folate", "Vitamin A", "Vitamin C"]
    },
    tags: ["iron-rich", "high-fiber", "budget-friendly", "anti-fatigue", "vegan"],
    benefits: ["Prevents iron-deficiency fatigue", "High folate for mental function", "Steady energy release", "Gut-friendly fiber"],
    suitableFor: ["students", "office-workers", "vegetarians", "budget-conscious"]
  },
  {
    id: "beef-broccoli-stir-fry",
    name: "Beef & Broccoli Stir-Fry",
    description: "Iron from beef paired with Vitamin C from broccoli ensures maximum absorption for alertness. Quick 15-minute energy meal.",
    cuisine: "chinese",
    category: "one-pot",
    cookingTime: 15,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: true,
    imageQuery: "Beef broccoli stir fry Chinese healthy iron vitamin C",
    sourceUrl: "https://www.recipetineats.com/chinese-beef-and-broccoli-extra-saucy-take-out-style/",
    ingredients: [
      { name: "Beef sirloin strips", amount: "300g", estimatedPrice: 4.50 },
      { name: "Broccoli florets", amount: "300g", estimatedPrice: 1.00 },
      { name: "Soy sauce", amount: "3 tbsp", estimatedPrice: 0.20 },
      { name: "Garlic cloves", amount: "3", estimatedPrice: 0.15 },
      { name: "Ginger", amount: "1 tbsp fresh", estimatedPrice: 0.25 },
      { name: "Sesame oil", amount: "1 tbsp", estimatedPrice: 0.30 },
      { name: "Cornflour", amount: "1 tsp", estimatedPrice: 0.05 },
      { name: "Rice (to serve)", amount: "200g cooked", estimatedPrice: 0.40 }
    ],
    instructions: [
      "Mix beef strips with 1 tbsp soy sauce and cornflour, set aside",
      "Heat sesame oil in wok or large pan over high heat",
      "Stir-fry beef for 2-3 minutes until browned, remove and set aside",
      "Add broccoli florets with 2 tbsp water, stir-fry for 4 minutes",
      "Add garlic and ginger, cook for 1 minute",
      "Return beef to pan, add remaining soy sauce, toss for 1 minute",
      "Serve immediately over rice"
    ],
    nutrition: {
      calories: 485,
      protein: 42,
      carbs: 45,
      fats: 18,
      fiber: 3,
      iron: 5.2,
      vitamins: ["Vitamin C", "B12", "K"]
    },
    tags: ["high-protein", "iron-rich", "quick-meal", "energy-boost", "vitamin-c"],
    benefits: ["Maximum iron absorption", "Vitamin C enhances alertness", "Quick energy", "Muscle recovery"],
    suitableFor: ["students", "office-workers", "athletes", "time-pressed"]
  },
  {
    id: "liver-onions",
    name: "Liver & Onions",
    description: "The ultimate B-vitamin boost for mental stamina. Traditional British dish packed with nutrients for peak cognitive performance.",
    cuisine: "british",
    category: "one-pot",
    cookingTime: 20,
    servings: 2,
    difficulty: "medium",
    spiceLevel: "mild",
    authentic: true,
    imageQuery: "Liver and onions British traditional food B vitamins",
    sourceUrl: "https://www.bbcgoodfoodme.com/recipes/liver-and-bacon-with-onion-gravy/",
    ingredients: [
      { name: "Lamb's liver", amount: "400g", estimatedPrice: 2.50 },
      { name: "Onions", amount: "2 large", estimatedPrice: 0.60 },
      { name: "Butter", amount: "50g", estimatedPrice: 0.40 },
      { name: "Plain flour", amount: "3 tbsp", estimatedPrice: 0.10 },
      { name: "Beef stock", amount: "200ml", estimatedPrice: 0.30 },
      { name: "Fresh thyme", amount: "2 sprigs", estimatedPrice: 0.20 },
      { name: "Mashed potato (to serve)", amount: "400g", estimatedPrice: 0.80 }
    ],
    instructions: [
      "Slice liver into strips, pat dry and dust with flour seasoned with salt and pepper",
      "Melt half the butter in a large pan, fry sliced onions until golden (10 minutes), remove",
      "Add remaining butter, increase heat to high",
      "Fry liver strips for 2 minutes each side until browned but still pink inside",
      "Return onions to pan, add stock and thyme",
      "Simmer for 2-3 minutes to create gravy",
      "Serve over creamy mashed potato"
    ],
    nutrition: {
      calories: 480,
      protein: 30,
      carbs: 45,
      fats: 19,
      fiber: 4,
      iron: 18.5,
      vitamins: ["B12", "B6", "Folate", "Vitamin A", "Riboflavin"]
    },
    tags: ["high-protein", "b-vitamins", "iron-powerhouse", "traditional", "mental-stamina"],
    benefits: ["Extreme B-vitamin content", "Combats mental fatigue", "Supports cognitive function", "Energy metabolism"],
    suitableFor: ["students", "office-workers", "exam-preparation", "high-performers"]
  },
  {
    id: "black-bean-sweet-potato-bowl",
    name: "Black Bean & Sweet Potato Burrito Bowl",
    description: "High fiber prevents the afternoon slump. Complex carbs and protein for sustained afternoon productivity.",
    cuisine: "mexican",
    category: "meal-prep",
    cookingTime: 30,
    servings: 3,
    difficulty: "easy",
    spiceLevel: "medium",
    authentic: false,
    imageQuery: "Black bean sweet potato burrito bowl Mexican healthy fiber",
    sourceUrl: "https://www.budgetbytes.com/sweet-potato-black-bean-skillet/",
    ingredients: [
      { name: "Sweet potatoes", amount: "500g", estimatedPrice: 1.00 },
      { name: "Black beans (tinned)", amount: "400g", estimatedPrice: 0.60 },
      { name: "Brown rice", amount: "200g", estimatedPrice: 0.50 },
      { name: "Red pepper", amount: "1", estimatedPrice: 0.80 },
      { name: "Avocado", amount: "1", estimatedPrice: 0.90 },
      { name: "Lime", amount: "1", estimatedPrice: 0.30 },
      { name: "Cumin", amount: "1 tsp", estimatedPrice: 0.10 },
      { name: "Paprika", amount: "1 tsp", estimatedPrice: 0.10 }
    ],
    instructions: [
      "Preheat oven to 200°C. Cube sweet potatoes and toss with oil, cumin, and paprika",
      "Roast sweet potatoes for 25 minutes until tender",
      "Meanwhile, cook brown rice according to package instructions",
      "Drain and rinse black beans, warm in a pan with a splash of water",
      "Dice red pepper and prepare avocado slices",
      "Assemble bowls: rice base, top with sweet potato, black beans, pepper, and avocado",
      "Squeeze lime juice over each bowl, season to taste"
    ],
    nutrition: {
      calories: 440,
      protein: 12,
      carbs: 70,
      fats: 14,
      fiber: 14,
      iron: 4.2,
      vitamins: ["Vitamin A", "Vitamin C", "B6"]
    },
    tags: ["high-fiber", "meal-prep", "vegan", "anti-slump", "complex-carbs"],
    benefits: ["Prevents afternoon energy crash", "18g fiber for sustained energy", "Blood sugar stability", "Gut health"],
    suitableFor: ["students", "office-workers", "meal-preppers", "vegetarians"]
  },
  {
    id: "sweet-potato-lentil-curry",
    name: "Sweet Potato & Lentil Curry",
    description: "Slow-burning fuel ideal for long work shifts. Warming spices boost circulation while lentils provide lasting energy.",
    cuisine: "indian",
    category: "one-pot",
    cookingTime: 35,
    servings: 4,
    difficulty: "easy",
    spiceLevel: "medium",
    authentic: true,
    imageQuery: "Sweet potato lentil curry Indian healthy work fuel",
    sourceUrl: "https://www.recipetineats.com/lentil-curry-mega-flavour-lentil-recipe/",
    ingredients: [
      { name: "Sweet potatoes", amount: "600g", estimatedPrice: 1.20 },
      { name: "Red lentils", amount: "200g", estimatedPrice: 0.65 },
      { name: "Coconut milk", amount: "400ml", estimatedPrice: 0.90 },
      { name: "Curry powder", amount: "2 tbsp", estimatedPrice: 0.20 },
      { name: "Onion", amount: "1 large", estimatedPrice: 0.30 },
      { name: "Garlic cloves", amount: "3", estimatedPrice: 0.15 },
      { name: "Ginger", amount: "1 tbsp fresh", estimatedPrice: 0.25 },
      { name: "Vegetable stock", amount: "400ml", estimatedPrice: 0.35 },
      { name: "Spinach", amount: "100g", estimatedPrice: 0.60 }
    ],
    instructions: [
      "Sauté diced onion in large pot until soft (5 minutes)",
      "Add garlic, ginger, and curry powder, cook for 1 minute",
      "Add cubed sweet potatoes and lentils, stir to coat in spices",
      "Pour in coconut milk and stock, bring to boil",
      "Reduce heat, simmer for 25 minutes until lentils and potatoes are tender",
      "Stir in spinach until wilted",
      "Serve with rice or naan bread"
    ],
    nutrition: {
      calories: 430,
      protein: 14,
      carbs: 50,
      fats: 22,
      fiber: 10,
      iron: 5.8,
      vitamins: ["Vitamin A", "Vitamin C", "Folate"]
    },
    tags: ["vegan", "high-fiber", "slow-energy", "warming", "shift-work"],
    benefits: ["Sustained energy for long shifts", "Anti-inflammatory spices", "Digestive support", "Blood sugar regulation"],
    suitableFor: ["students", "shift-workers", "office-workers", "vegetarians"]
  },
  {
    id: "buckwheat-pancakes-cinnamon",
    name: "Buckwheat Pancakes with Cinnamon",
    description: "Buckwheat regulates blood sugar to prevent crashes. Perfect breakfast for stable morning energy and focus.",
    cuisine: "american",
    category: "one-pot",
    cookingTime: 15,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Buckwheat pancakes cinnamon healthy breakfast blood sugar",
    sourceUrl: "https://minimalistbaker.com/5-ingredient-buckwheat-crepes/",
    ingredients: [
      { name: "Buckwheat flour", amount: "150g", estimatedPrice: 1.20 },
      { name: "Eggs", amount: "2", estimatedPrice: 0.40 },
      { name: "Milk", amount: "200ml", estimatedPrice: 0.30 },
      { name: "Cinnamon", amount: "2 tsp", estimatedPrice: 0.15 },
      { name: "Baking powder", amount: "1 tsp", estimatedPrice: 0.05 },
      { name: "Butter (for cooking)", amount: "20g", estimatedPrice: 0.15 },
      { name: "Greek yogurt", amount: "100g", estimatedPrice: 0.50 },
      { name: "Berries", amount: "100g", estimatedPrice: 1.20 }
    ],
    instructions: [
      "Whisk together buckwheat flour, cinnamon, and baking powder",
      "In separate bowl, beat eggs and milk together",
      "Combine wet and dry ingredients, mix until smooth batter forms",
      "Heat butter in non-stick pan over medium heat",
      "Pour 3 tbsp batter per pancake, cook for 2 minutes until bubbles form",
      "Flip and cook for another 2 minutes until golden",
      "Serve with Greek yogurt and fresh berries"
    ],
    nutrition: {
      calories: 380,
      protein: 16,
      carbs: 50,
      fats: 13,
      fiber: 6,
      iron: 2.8,
      vitamins: ["B-complex", "Magnesium", "Manganese"]
    },
    tags: ["breakfast", "blood-sugar-friendly", "gluten-free-option", "energy-stable", "quick"],
    benefits: ["Prevents blood sugar spikes", "Sustained morning energy", "Rich in minerals", "Heart-healthy"],
    suitableFor: ["students", "office-workers", "diabetic-friendly", "health-conscious"]
  },
  {
    id: "miso-glazed-halibut",
    name: "Miso Glazed Halibut",
    description: "Fermented foods support the gut-brain axis for mental clarity. Omega-3 rich fish enhances cognitive function.",
    cuisine: "japanese",
    category: "one-pot",
    cookingTime: 20,
    servings: 2,
    difficulty: "medium",
    spiceLevel: "mild",
    authentic: true,
    imageQuery: "Miso glazed halibut Japanese fish gut brain health",
    sourceUrl: "https://www.recipetineats.com/miso-marinated-side-of-salmon/",
    ingredients: [
      { name: "Halibut fillets", amount: "2 x 150g", estimatedPrice: 6.00 },
      { name: "White miso paste", amount: "3 tbsp", estimatedPrice: 0.80 },
      { name: "Mirin", amount: "2 tbsp", estimatedPrice: 0.40 },
      { name: "Honey", amount: "1 tbsp", estimatedPrice: 0.15 },
      { name: "Rice wine vinegar", amount: "1 tbsp", estimatedPrice: 0.20 },
      { name: "Spring onions", amount: "2", estimatedPrice: 0.30 },
      { name: "Sesame seeds", amount: "1 tsp", estimatedPrice: 0.10 },
      { name: "Steamed rice", amount: "200g cooked", estimatedPrice: 0.40 }
    ],
    instructions: [
      "Mix miso paste, mirin, honey, and rice vinegar to create glaze",
      "Pat halibut fillets dry, brush generously with half the miso glaze",
      "Marinate for 10 minutes if time allows",
      "Preheat grill to medium-high, line tray with foil",
      "Grill halibut for 8-10 minutes, brushing with remaining glaze halfway",
      "Fish should be opaque and flake easily when done",
      "Garnish with sliced spring onions and sesame seeds, serve over rice"
    ],
    nutrition: {
      calories: 400,
      protein: 35,
      carbs: 45,
      fats: 10,
      fiber: 1,
      iron: 1.5,
      vitamins: ["B12", "Vitamin D", "Selenium", "Omega-3"]
    },
    tags: ["high-protein", "omega-3", "gut-health", "fermented", "brain-food"],
    benefits: ["Gut-brain axis support", "Mental clarity", "Anti-inflammatory", "Probiotic benefits"],
    suitableFor: ["students", "office-workers", "health-conscious", "pescatarians"]
  },
  {
    id: "mediterranean-chickpea-salad",
    name: "Mediterranean Chickpea Salad",
    description: "Light enough to prevent drowsiness, hearty enough to fuel you. Perfect lunch that won't cause afternoon fatigue.",
    cuisine: "mediterranean",
    category: "meal-prep",
    cookingTime: 10,
    servings: 3,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: true,
    imageQuery: "Mediterranean chickpea salad healthy light lunch energy",
    sourceUrl: "https://www.budgetbytes.com/spinach-chickpea-and-quinoa-salad/",
    ingredients: [
      { name: "Chickpeas (tinned)", amount: "400g", estimatedPrice: 0.60 },
      { name: "Cherry tomatoes", amount: "200g", estimatedPrice: 1.00 },
      { name: "Cucumber", amount: "1", estimatedPrice: 0.60 },
      { name: "Red onion", amount: "1 small", estimatedPrice: 0.25 },
      { name: "Feta cheese", amount: "100g", estimatedPrice: 1.20 },
      { name: "Olive oil", amount: "3 tbsp", estimatedPrice: 0.30 },
      { name: "Lemon juice", amount: "2 tbsp", estimatedPrice: 0.15 },
      { name: "Fresh parsley", amount: "20g", estimatedPrice: 0.40 }
    ],
    instructions: [
      "Drain and rinse chickpeas thoroughly",
      "Halve cherry tomatoes, dice cucumber, and thinly slice red onion",
      "Combine all vegetables and chickpeas in large bowl",
      "Crumble feta cheese over the salad",
      "Whisk together olive oil, lemon juice, salt, and pepper",
      "Pour dressing over salad and toss gently",
      "Garnish with chopped fresh parsley",
      "Can be refrigerated for up to 3 days"
    ],
    nutrition: {
      calories: 310,
      protein: 12,
      carbs: 30,
      fats: 16,
      fiber: 9,
      iron: 3.2,
      vitamins: ["Vitamin C", "Folate", "Calcium"]
    },
    tags: ["no-cook", "meal-prep", "light-lunch", "no-drowsiness", "vegetarian"],
    benefits: ["Prevents food coma", "Light but satisfying", "Portable lunch", "Brain-boosting fats"],
    suitableFor: ["students", "office-workers", "meal-preppers", "desk-lunches"]
  },
  {
    id: "soba-noodle-salad-edamame",
    name: "Soba Noodle Salad with Edamame",
    description: "Buckwheat provides energy without sugar spikes. Complete plant protein from edamame for sustained work performance.",
    cuisine: "japanese",
    category: "meal-prep",
    cookingTime: 15,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: true,
    imageQuery: "Soba noodle salad edamame Japanese healthy buckwheat",
    sourceUrl: "https://www.budgetbytes.com/peanut-soba-stir-fry/",
    ingredients: [
      { name: "Soba noodles", amount: "200g", estimatedPrice: 1.50 },
      { name: "Edamame beans", amount: "150g frozen", estimatedPrice: 1.20 },
      { name: "Carrot", amount: "1 large", estimatedPrice: 0.30 },
      { name: "Red pepper", amount: "1", estimatedPrice: 0.80 },
      { name: "Soy sauce", amount: "3 tbsp", estimatedPrice: 0.20 },
      { name: "Rice vinegar", amount: "2 tbsp", estimatedPrice: 0.20 },
      { name: "Sesame oil", amount: "1 tbsp", estimatedPrice: 0.30 },
      { name: "Sesame seeds", amount: "1 tbsp", estimatedPrice: 0.15 }
    ],
    instructions: [
      "Cook soba noodles according to package instructions, drain and rinse under cold water",
      "Boil edamame beans for 3 minutes, drain and cool",
      "Julienne carrot and red pepper into thin strips",
      "Make dressing: whisk together soy sauce, rice vinegar, and sesame oil",
      "Combine noodles, edamame, and vegetables in large bowl",
      "Pour dressing over and toss well",
      "Garnish with sesame seeds, serve cold or at room temperature"
    ],
    nutrition: {
      calories: 424,
      protein: 15,
      carbs: 56,
      fats: 18,
      fiber: 6,
      iron: 3.8,
      vitamins: ["Vitamin A", "Vitamin C", "Folate"]
    },
    tags: ["plant-protein", "blood-sugar-friendly", "meal-prep", "cold-lunch", "vegan"],
    benefits: ["No sugar crash", "Complete plant protein", "Sustained energy", "Portable meal"],
    suitableFor: ["students", "office-workers", "vegetarians", "meal-preppers"]
  },
  {
    id: "cauliflower-rice-risotto-shrimp",
    name: "Cauliflower Rice Risotto with Shrimp",
    description: "Light meal prevents food coma digestion issues. Low-carb option keeps you alert and productive after lunch.",
    cuisine: "italian",
    category: "one-pot",
    cookingTime: 25,
    servings: 2,
    difficulty: "medium",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Cauliflower rice risotto shrimp low carb Italian healthy",
    sourceUrl: "https://www.recipetineats.com/prawn-risotto-shrimp/",
    ingredients: [
      { name: "Cauliflower rice", amount: "400g", estimatedPrice: 1.50 },
      { name: "King prawns", amount: "200g", estimatedPrice: 3.50 },
      { name: "Parmesan cheese", amount: "50g grated", estimatedPrice: 0.80 },
      { name: "Garlic cloves", amount: "3", estimatedPrice: 0.15 },
      { name: "White wine", amount: "100ml", estimatedPrice: 0.50 },
      { name: "Vegetable stock", amount: "200ml", estimatedPrice: 0.20 },
      { name: "Butter", amount: "30g", estimatedPrice: 0.25 },
      { name: "Fresh parsley", amount: "15g", estimatedPrice: 0.30 }
    ],
    instructions: [
      "Sauté prawns in half the butter for 2 minutes each side, remove and set aside",
      "In same pan, add remaining butter and minced garlic, cook 1 minute",
      "Add cauliflower rice, stir-fry for 3 minutes",
      "Pour in white wine, let it reduce for 2 minutes",
      "Gradually add stock, stirring frequently, cook for 10 minutes",
      "Stir in Parmesan cheese until melted and creamy",
      "Return prawns to pan, heat through for 2 minutes",
      "Garnish with fresh parsley"
    ],
    nutrition: {
      calories: 290,
      protein: 24,
      carbs: 12,
      fats: 15,
      fiber: 4,
      iron: 2.8,
      vitamins: ["Vitamin C", "B12", "Selenium"]
    },
    tags: ["low-carb", "high-protein", "no-food-coma", "keto-friendly", "light-lunch"],
    benefits: ["Prevents afternoon drowsiness", "Low-carb energy", "Quick digestion", "Mental clarity"],
    suitableFor: ["students", "office-workers", "keto-dieters", "health-conscious"]
  },
  {
    id: "bean-egg-breakfast-burrito",
    name: "Bean & Egg Breakfast Burrito",
    description: "Fiber-rich beans keep energy stable all morning. Protein from eggs provides sustained satiety for busy work mornings.",
    cuisine: "mexican",
    category: "one-pot",
    cookingTime: 15,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "medium",
    authentic: false,
    imageQuery: "Bean egg breakfast burrito Mexican healthy fiber protein",
    sourceUrl: "https://www.budgetbytes.com/freezer-breakfast-burritos/",
    ingredients: [
      { name: "Eggs", amount: "4", estimatedPrice: 0.80 },
      { name: "Black beans (tinned)", amount: "200g", estimatedPrice: 0.30 },
      { name: "Tortilla wraps", amount: "2 large", estimatedPrice: 0.50 },
      { name: "Cheddar cheese", amount: "60g grated", estimatedPrice: 0.70 },
      { name: "Red pepper", amount: "1", estimatedPrice: 0.80 },
      { name: "Spring onions", amount: "2", estimatedPrice: 0.30 },
      { name: "Smoked paprika", amount: "1 tsp", estimatedPrice: 0.10 },
      { name: "Salsa", amount: "4 tbsp", estimatedPrice: 0.40 }
    ],
    instructions: [
      "Drain beans and warm in pan with paprika for 3 minutes, mash slightly",
      "Dice red pepper and slice spring onions",
      "Beat eggs, scramble in pan with peppers until just set (3-4 minutes)",
      "Warm tortillas in microwave for 20 seconds",
      "Spread bean mixture down center of each tortilla",
      "Top with scrambled eggs, cheese, spring onions, and salsa",
      "Fold in sides and roll tightly into burrito",
      "Optional: toast in dry pan for 2 minutes for crispy exterior"
    ],
    nutrition: {
      calories: 465,
      protein: 28,
      carbs: 42,
      fats: 20,
      fiber: 10,
      iron: 4.5,
      vitamins: ["B12", "Folate", "Vitamin C"]
    },
    tags: ["breakfast", "high-protein", "high-fiber", "grab-and-go", "portable"],
    benefits: ["All-morning satiety", "Stable blood sugar", "Portable breakfast", "Complete nutrition"],
    suitableFor: ["students", "office-workers", "busy-mornings", "commuters"]
  },
  {
    id: "minestrone-soup",
    name: "Minestrone Soup",
    description: "Varied vegetable antioxidants for overall vitality. Traditional Italian soup packed with nutrients for sustained work energy.",
    cuisine: "italian",
    category: "one-pot",
    cookingTime: 40,
    servings: 5,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: true,
    imageQuery: "Minestrone soup Italian healthy vegetable antioxidants",
    sourceUrl: "https://www.recipetineats.com/minestrone-soup/",
    ingredients: [
      { name: "Chopped tomatoes (tinned)", amount: "400g", estimatedPrice: 0.50 },
      { name: "Mixed vegetables (carrot, celery, courgette)", amount: "400g", estimatedPrice: 1.20 },
      { name: "Cannellini beans (tinned)", amount: "400g", estimatedPrice: 0.60 },
      { name: "Small pasta shapes", amount: "100g", estimatedPrice: 0.30 },
      { name: "Vegetable stock", amount: "1.5L", estimatedPrice: 0.60 },
      { name: "Onion", amount: "1", estimatedPrice: 0.30 },
      { name: "Garlic cloves", amount: "3", estimatedPrice: 0.15 },
      { name: "Fresh basil", amount: "15g", estimatedPrice: 0.50 },
      { name: "Parmesan rind", amount: "1 piece (optional)", estimatedPrice: 0.30 }
    ],
    instructions: [
      "Sauté diced onion in large pot until soft (5 minutes)",
      "Add minced garlic, diced carrot, and celery, cook for 5 minutes",
      "Add chopped tomatoes, stock, and Parmesan rind if using",
      "Bring to boil, then simmer for 20 minutes",
      "Add diced courgette and pasta, cook for 10 minutes",
      "Stir in drained cannellini beans, heat through for 2 minutes",
      "Remove Parmesan rind, season to taste",
      "Serve with fresh basil and grated Parmesan"
    ],
    nutrition: {
      calories: 246,
      protein: 14,
      carbs: 29,
      fats: 9,
      fiber: 5,
      iron: 3.5,
      vitamins: ["Vitamin A", "Vitamin C", "Folate", "Lycopene"]
    },
    tags: ["vegan-option", "high-fiber", "antioxidant-rich", "meal-prep", "budget-friendly"],
    benefits: ["Multiple antioxidant sources", "Gut health", "Immune support", "Low-calorie energy"],
    suitableFor: ["students", "office-workers", "budget-conscious", "meal-preppers"]
  },
  {
    id: "pesto-zucchini-noodles-chicken",
    name: "Pesto Zucchini Noodles with Chicken",
    description: "Low-carb option to avoid heaviness during work. Light but protein-rich meal maintains afternoon alertness.",
    cuisine: "italian",
    category: "one-pot",
    cookingTime: 20,
    servings: 2,
    difficulty: "easy",
    spiceLevel: "mild",
    authentic: false,
    imageQuery: "Pesto zucchini noodles chicken low carb Italian healthy",
    sourceUrl: "https://www.budgetbytes.com/easy-pesto-chicken-and-vegetables/",
    ingredients: [
      { name: "Courgettes (zucchini)", amount: "3 large", estimatedPrice: 1.20 },
      { name: "Chicken breast", amount: "2 x 150g", estimatedPrice: 3.00 },
      { name: "Fresh basil pesto", amount: "4 tbsp", estimatedPrice: 1.20 },
      { name: "Cherry tomatoes", amount: "150g", estimatedPrice: 0.80 },
      { name: "Garlic cloves", amount: "2", estimatedPrice: 0.10 },
      { name: "Olive oil", amount: "2 tbsp", estimatedPrice: 0.20 },
      { name: "Parmesan cheese", amount: "30g", estimatedPrice: 0.50 },
      { name: "Pine nuts", amount: "20g", estimatedPrice: 0.60 }
    ],
    instructions: [
      "Spiralize courgettes into noodles or use vegetable peeler for ribbons",
      "Season and pan-fry chicken breasts in 1 tbsp oil for 6 minutes each side until cooked through",
      "Remove chicken, slice, and keep warm",
      "In same pan, add remaining oil and minced garlic, cook 30 seconds",
      "Add halved cherry tomatoes, cook for 2 minutes",
      "Add courgette noodles, toss for 2-3 minutes until just tender",
      "Remove from heat, stir in pesto",
      "Top with sliced chicken, Parmesan, and toasted pine nuts"
    ],
    nutrition: {
      calories: 380,
      protein: 38,
      carbs: 10,
      fats: 22,
      fiber: 4,
      iron: 2.5,
      vitamins: ["Vitamin C", "Vitamin A", "B6"]
    },
    tags: ["low-carb", "high-protein", "keto-friendly", "light-lunch", "gluten-free"],
    benefits: ["No afternoon heaviness", "High protein keeps you full", "Mental clarity", "Quick energy"],
    suitableFor: ["students", "office-workers", "keto-dieters", "low-carb"]
  },
  {
    id: "chili-con-carne",
    name: "Rice & Beans (Chili Con Carne)",
    description: "A classic energy staple. Complete protein with slow-release carbs for all-day sustained work performance.",
    cuisine: "mexican",
    category: "one-pot",
    cookingTime: 40,
    servings: 4,
    difficulty: "easy",
    spiceLevel: "medium",
    authentic: true,
    imageQuery: "Chili con carne rice beans Mexican energy staple",
    sourceUrl: "https://www.recipetineats.com/chilli-con-carne/",
    ingredients: [
      { name: "Lean beef mince", amount: "500g", estimatedPrice: 3.50 },
      { name: "Kidney beans (tinned)", amount: "400g", estimatedPrice: 0.60 },
      { name: "Chopped tomatoes (tinned)", amount: "400g", estimatedPrice: 0.50 },
      { name: "Onion", amount: "1 large", estimatedPrice: 0.30 },
      { name: "Garlic cloves", amount: "3", estimatedPrice: 0.15 },
      { name: "Chili powder", amount: "2 tbsp", estimatedPrice: 0.20 },
      { name: "Cumin", amount: "1 tbsp", estimatedPrice: 0.15 },
      { name: "Brown rice", amount: "300g", estimatedPrice: 0.75 },
      { name: "Beef stock", amount: "200ml", estimatedPrice: 0.30 }
    ],
    instructions: [
      "Cook brown rice according to package instructions",
      "Brown beef mince in large pot, breaking up lumps (5 minutes)",
      "Add diced onion and garlic, cook until soft (5 minutes)",
      "Stir in chili powder and cumin, cook for 1 minute",
      "Add chopped tomatoes, drained kidney beans, and stock",
      "Bring to boil, then reduce heat and simmer for 25 minutes",
      "Season to taste, serve over rice",
      "Optional toppings: sour cream, cheese, coriander"
    ],
    nutrition: {
      calories: 540,
      protein: 38,
      carbs: 68,
      fats: 12,
      fiber: 12,
      iron: 6.8,
      vitamins: ["B12", "Zinc", "Folate"]
    },
    tags: ["high-protein", "high-fiber", "meal-prep", "complete-protein", "energy-staple"],
    benefits: ["All-day sustained energy", "Complete amino acid profile", "Muscle recovery", "Iron-rich"],
    suitableFor: ["students", "office-workers", "athletes", "meal-preppers"]
  },
  {
    id: "vietnamese-summer-rolls",
    name: "Vietnamese Summer Rolls",
    description: "Fresh and light for quick energy. Raw vegetables and lean protein provide instant vitality without heaviness.",
    cuisine: "chinese",
    category: "meal-prep",
    cookingTime: 20,
    servings: 3,
    difficulty: "medium",
    spiceLevel: "mild",
    authentic: true,
    imageQuery: "Vietnamese summer rolls fresh healthy light energy",
    sourceUrl: "https://www.recipetineats.com/vietnamese-rice-paper-rolls-spring-rolls/",
    ingredients: [
      { name: "Rice paper wrappers", amount: "12 sheets", estimatedPrice: 1.50 },
      { name: "Cooked prawns", amount: "200g", estimatedPrice: 2.50 },
      { name: "Rice vermicelli noodles", amount: "100g", estimatedPrice: 0.80 },
      { name: "Carrots", amount: "2", estimatedPrice: 0.60 },
      { name: "Cucumber", amount: "1", estimatedPrice: 0.60 },
      { name: "Fresh mint", amount: "20g", estimatedPrice: 0.50 },
      { name: "Fresh coriander", amount: "20g", estimatedPrice: 0.50 },
      { name: "Peanut butter (for dipping sauce)", amount: "3 tbsp", estimatedPrice: 0.40 },
      { name: "Soy sauce", amount: "2 tbsp", estimatedPrice: 0.15 }
    ],
    instructions: [
      "Cook rice noodles according to package, drain and cool",
      "Julienne carrots and cucumber into thin strips",
      "Prepare dipping sauce: mix peanut butter, soy sauce, and warm water until smooth",
      "Dip one rice paper in warm water for 5 seconds until pliable",
      "Lay on clean surface, add small portion of noodles, prawns, vegetables, and herbs",
      "Fold in sides and roll tightly like a burrito",
      "Repeat with remaining wrappers",
      "Serve immediately with peanut dipping sauce"
    ],
    nutrition: {
      calories: 230,
      protein: 15,
      carbs: 30,
      fats: 7,
      fiber: 3,
      iron: 2.2,
      vitamins: ["Vitamin A", "Vitamin C", "B12"]
    },
    tags: ["no-cook", "light-meal", "fresh", "quick-energy", "portable"],
    benefits: ["Instant energy", "Light and refreshing", "Easy digestion", "Hydrating vegetables"],
    suitableFor: ["students", "office-workers", "hot-weather", "light-eaters"]
  }
];
